### PR TITLE
change module to ThreeDotsLabs/watermill-jetstream

### PR DESCRIPTION
**Pull request by AlexCuse**

### CODE REVIEW

**Comment by AlexCuse** [comment]
@ma-hartma FYI - you should just be able to repoint your upstream.

**Comment by ma-hartma** [comment]
@AlexCuse Thanks! Cool, that this is an official implementation now! :)

**Comment by ma-hartma** [comment]
@AlexCuse could you please tag the current version as a release since go mod will throw following error:

```
go: downloading github.com/ThreeDotsLabs/watermill-jetstream v0.0.4
go: github.com/ThreeDotsLabs/watermill-jetstream@v0.0.4: parsing go.mod:
        module declares its path as: github.com/AlexCuse/watermill-jetstream
                but was required as: github.com/ThreeDotsLabs/watermill-jetstream
```

**Comment by AlexCuse** [comment]
Done just wanted to merge the proto thing first.

**Pull request merged**
